#!/bin/bash

#import bashsimplecurses
source $(dirname $0)/bashsimplecurses/simple_curses.sh


main(){

	clear 
	statut=$(cat etat)
    	
if [ $statut = "ROUGE" ] ; then 	
	window "Controle des trains" "red" "100%"
    	append "UN TRAIN A ETE ANNULE"
    	endwin
fi

if [ $statut = "ORANGE" ] ; then
        window "Controle des trains" "orange" "100%"
        append "UN TRAIN EST EN RETARD"
        endwin
fi

if [ $statut = "VERT" ] ; then
        window "Controle des trains" "green" "100%"
        append "Aucun probleme de train"
        endwin
fi


    window "Heure" "blue" "50%"
    append "`date '+%H : %M'`"
    endwin

    window "GMAIL" "blue" "100%"
    append_file "gmail"
    endwin


}
main_loop
